In [29]:
import sys
from pathlib import Path
import json
from collections import Counter
import geopandas as gpd

# adiciona a raiz do projeto ao Python
sys.path.append(str(Path.cwd().parent))

from src.domain.enums import IncomeGroup, TravelMode, TripPurpose
from src.domain.agent import Agent
from src.simulation.population import generate_population

In [7]:
# Testando enum
print(IncomeGroup.LOW)
print(IncomeGroup.LOW.value)

print(TravelMode.CAR)
print(TripPurpose.WORK)

print(IncomeGroup("low"))
print(TravelMode("bike"))
print(TripPurpose("education"))

IncomeGroup.LOW
low
TravelMode.CAR
TripPurpose.WORK
IncomeGroup.LOW
TravelMode.BIKE
TripPurpose.EDUCATION

In [10]:
# Testando agent
agent = Agent(
    agent_id=1,
    income_group=IncomeGroup.LOW
)

agent

Agent(agent_id=1, income_group=<IncomeGroup.LOW: 'low'>, origin_id=None, origin_node=None, purpose=None, destination_id=None, destination_node=None, mode=None, route_edges=[], travel_distance=None, travel_time=None)

In [13]:
print(agent.agent_id)
print(agent.income_group)
print(agent.income_group.value)
print(agent.origin_node)
print(agent.route_edges)

agent.origin_id = 15
agent.origin_node = 123456789

print(agent)

1
IncomeGroup.LOW
low
123456789
[]
Agent(agent_id=1, income_group=<IncomeGroup.LOW: 'low'>, origin_id=15, origin_node=123456789, purpose=None, destination_id=None, destination_node=None, mode=None, route_edges=[], travel_distance=None, travel_time=None)

In [18]:
PROJECT_ROOT = Path.cwd().parent

CONFIG_PATH = (
    PROJECT_ROOT
    / "config" / "config.json"
)

with open(
    CONFIG_PATH,
    "r",
    encoding="utf-8"
) as f:

    config = json.load(f)

In [19]:
income_groups_config = (
    config["income"]["groups"]
)

income_shares = {
    IncomeGroup.LOW:
        income_groups_config["low"]["share"],

    IncomeGroup.MIDDLE:
        income_groups_config["middle"]["share"],

    IncomeGroup.HIGH:
        income_groups_config["high"]["share"],
}

income_shares

{<IncomeGroup.LOW: 'low'>: 0.20997644,
 <IncomeGroup.MIDDLE: 'middle'>: 0.61144735,
 <IncomeGroup.HIGH: 'high'>: 0.17857621}

In [20]:
agents = generate_population(
    n_agents=1000,
    income_shares=income_shares,
    seed=42
)

In [22]:
counts = Counter(
    agent.income_group.value
    for agent in agents
)

counts

Counter({'middle': 611, 'low': 210, 'high': 179})

In [24]:
for group, count in counts.items():

    print(
        group,
        count,
        round(
            count / len(agents),
            4
        )
    )

high 179 0.179
low 210 0.21
middle 611 0.611

In [25]:
agents_42 = generate_population(
    n_agents=1000,
    income_shares=income_shares,
    seed=42
)

agents_123 = generate_population(
    n_agents=1000,
    income_shares=income_shares,
    seed=123
)

In [ ]:
origins_path = (
    PROJECT_ROOT
    / config["paths"]["origins"]
)

origins = gpd.read_file(
    origins_path
)

print("CRS:", origins.crs)
print("Quantidade:", len(origins))
print("\nColunas:")
print(origins.columns.tolist())

display(
    origins.head()
)

CRS: EPSG:31982
Quantidade: 6189

Colunas:
['origin_id', 'ID_UNICO', 'nome_1KM', 'nome_5KM', 'nome_10KM', 'nome_50KM', 'nome_100KM', 'nome_500KM', 'QUADRANTE', 'MASC', 'FEM', 'POP', 'DOM_OCU', 'Shape_Leng', 'Shape_Area', 'node', 'geometry']

,origin_id,ID_UNICO,nome_1KM,nome_5KM,nome_10KM,nome_50KM,nome_100KM,nome_500KM,QUADRANTE,MASC,FEM,POP,DOM_OCU,Shape_Leng,Shape_Area,node,geometry
0,235.0,200ME52736N79976,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,26.0,29.0,55.0,16.0,0.007743,0.000004,2248442166,POINT (474386.204 6669552.438)
1,236.0,200ME52738N79976,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,50.0,55.0,105.0,30.0,0.007743,0.000004,296249745,POINT (474578.68 6669554.914)
2,237.0,200ME52736N79978,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,46.0,51.0,97.0,28.0,0.007743,0.000004,2248442166,POINT (474383.84 6669760.062)
3,238.0,200ME52738N79978,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,55.0,59.0,114.0,33.0,0.007743,0.000004,508060554,POINT (474576.318 6669762.539)
4,239.0,200ME52736N79980,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,37.0,43.0,80.0,23.0,0.007743,0.000004,583532859,POINT (474381.475 6669967.684)

KeyError: 'income_group'

In [36]:
print("CRS:")
print(origins.crs)

print("\nQuantidade de origens:")
print(len(origins))

print("\nTipo de geometria:")
print(origins.geometry.geom_type.value_counts())

print("\nColunas:")
print(origins.columns.tolist())

display(
    origins.head()
)

CRS:
EPSG:31982

Quantidade de origens:
6189

Tipo de geometria:
Point    6189
Name: count, dtype: int64

Colunas:
['origin_id', 'ID_UNICO', 'nome_1KM', 'nome_5KM', 'nome_10KM', 'nome_50KM', 'nome_100KM', 'nome_500KM', 'QUADRANTE', 'MASC', 'FEM', 'POP', 'DOM_OCU', 'Shape_Leng', 'Shape_Area', 'node', 'geometry']

,origin_id,ID_UNICO,nome_1KM,nome_5KM,nome_10KM,nome_50KM,nome_100KM,nome_500KM,QUADRANTE,MASC,FEM,POP,DOM_OCU,Shape_Leng,Shape_Area,node,geometry
0,235.0,200ME52736N79976,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,26.0,29.0,55.0,16.0,0.007743,0.000004,2248442166,POINT (474386.204 6669552.438)
1,236.0,200ME52738N79976,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,50.0,55.0,105.0,30.0,0.007743,0.000004,296249745,POINT (474578.68 6669554.914)
2,237.0,200ME52736N79978,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,46.0,51.0,97.0,28.0,0.007743,0.000004,2248442166,POINT (474383.84 6669760.062)
3,238.0,200ME52738N79978,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,55.0,59.0,114.0,33.0,0.007743,0.000004,508060554,POINT (474576.318 6669762.539)
4,239.0,200ME52736N79980,1KME5273N7997,5KME5270N7995,10KME5270N7990,50KME5250N7950,100KME5200N7950,500KME4800N7850,ID_14,37.0,43.0,80.0,23.0,0.007743,0.000004,583532859,POINT (474381.475 6669967.684)

In [38]:
origins.info()
origins.columns.tolist()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 6189 entries, 0 to 6188
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   origin_id   6189 non-null   float64
 1   ID_UNICO    6189 non-null   str
 2   nome_1KM    6189 non-null   str
 3   nome_5KM    6189 non-null   str
 4   nome_10KM   6189 non-null   str
 5   nome_50KM   6189 non-null   str
 6   nome_100KM  6189 non-null   str
 7   nome_500KM  6189 non-null   str
 8   QUADRANTE   6189 non-null   str
 9   MASC        6189 non-null   float64
 10  FEM         6189 non-null   float64
 11  POP         6189 non-null   float64
 12  DOM_OCU     6189 non-null   float64
 13  Shape_Leng  6189 non-null   float64
 14  Shape_Area  6189 non-null   float64
 15  node        6189 non-null   int64
 16  geometry    6189 non-null   geometry
dtypes: float64(7), geometry(1), int64(1), str(8)
memory usage: 1.4 MB

['origin_id',
 'ID_UNICO',
 'nome_1KM',
 'nome_5KM',
 'nome_10KM',
 'nome_50KM',
 'nome_100KM',
 'nome_500KM',
 'QUADRANTE',
 'MASC',
 'FEM',
 'POP',
 'DOM_OCU',
 'Shape_Leng',
 'Shape_Area',
 'node',
 'geometry']